- name: Instalar Agent Puppet Debian
  apt:
    name: puppet-agent             
    update_cache: yes
    state: present
  when: ansible_os_family == 'Debian'

- name: Instalar Agent Puppet RedHat
  yum:
    name: puppet-agent                                         
    state: present
  when: ansible_os_family == 'RedHat'
