---
  - name: Apache
    hosts: all
    tasks:
      - name: Instalar Debian
        apt:
          name: apache2
          state: present
        when: ansible_os_family == 'Debian' 

      - name: Instalar Red Hat
        yum:
          name: httpd
          state: present
        when: ansible_os_family == 'RedHat'

      - name: Copiando Index
        copy:
          src: index.html
          dest: /var/www/html/index.html

      - name: Reiniciar Apache Debian
        service:
          name: apache2
          state: restarted
        when: ansible_os_family == 'Debian'

      - name: Reiniciar Apache RedHat
        service:
          name: httpd
          state: restarted
        when: ansible_os_family == 'RedHat'
...
